export default [
  { value: 'Rice', categories: ['Type:Grain', 'Size:Small'] },
  { value: 'Anchovy', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Herring', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Bay Shrimp', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Clam', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Cuttlefish', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Hard-Shell Clam', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Common Mussel', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Oyster', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Squid', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Urchin', categories: ['Type:Fish', 'Size:Small'] },
  { value: 'Eel', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Flounder', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Mackerel', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Sole', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Blue Salmon', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Sockeye Salmon', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Black Tiger Shrimp', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Lobster', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Octopus', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Scallop', categories: ['Type:Fish', 'Size:Medium'] },
  { value: 'Char', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Cobia', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Cod', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Haddock', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Halibut', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'King Salmon', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Mahi-Mahi', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Giant Scallop', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Snow Crab', categories: ['Type:Fish', 'Size:Large'] },
  { value: 'Albacore Tuna', categories: ['Type:Fish', 'Size:Huge'] },
  { value: 'Bluefin Tuna', categories: ['Type:Fish', 'Size:Huge'] },
  { value: 'Yellowfin Tuna', categories: ['Type:Fish', 'Size:Huge'] }
]
